name: picturearchiveorganiser
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^3.0.3
  go_router: ^16.2.5
  riverpod_annotation: ^3.0.3
  file_picker: ^6.2.0
  exif: ^3.1.3
  crypto: ^3.0.3
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  riverpod_generator: ^3.0.3

flutter:
  uses-material-design: true
